import type {House, Testimonial, Plot} from "../lib/types";
export const houses: House[] = [
  {
    id: "house-001",
    title: "Modern Villa in Kiyovu",
    price: 180000000,
    bedrooms: 4,
    bathrooms: 3,
    size: 350,
    location: "Kiyovu, Nyarugenge",
    coordinates: { lat: -1.9536, lng: 30.0606 },
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Stunning modern villa with contemporary design and premium finishes in prestigious Kiyovu.",
    features: ["Swimming Pool", "Garden", "Parking for 2 Cars", "Modern Kitchen", "Security System", "Balcony"],
    type: "villa",
    status: "available",
    createdAt: "2024-01-18",
  },
  {
    id: "house-002",
    title: "Family Townhouse in Remera",
    price: 95000000,
    bedrooms: 3,
    bathrooms: 2,
    size: 220,
    location: "Remera, Gasabo",
    coordinates: { lat: -1.9333, lng: 30.1 },
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Perfect family home in quiet Remera neighborhood with easy access to schools and shopping.",
    features: ["Front Yard", "Parking", "Modern Appliances", "Close to Schools", "Public Transport"],
    type: "townhouse",
    status: "available",
    createdAt: "2024-01-12",
  },
  {
    id: "house-003",
    title: "Luxury Apartment in Kimihurura",
    price: 75000000,
    bedrooms: 2,
    bathrooms: 2,
    size: 150,
    location: "Kimihurura, Gasabo",
    coordinates: { lat: -1.9167, lng: 30.0833 },
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Elegant apartment with city views and modern amenities in the heart of Kimihurura.",
    features: ["City View", "Elevator", "Gym Access", "Parking", "Security", "24/7 Concierge"],
    type: "apartment",
    status: "available",
    createdAt: "2024-01-08",
  },
  {
    id: "house-004",
    title: "Executive Duplex in Gacuriro",
    price: 140000000,
    bedrooms: 5,
    bathrooms: 4,
    size: 400,
    location: "Gacuriro, Gasabo",
    coordinates: { lat: -1.9167, lng: 30.1333 },
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Spacious executive duplex perfect for large families, featuring premium finishes throughout.",
    features: ["Double Garage", "Master Suite", "Study Room", "Maid's Quarter", "Generator", "Water Tank"],
    type: "duplex",
    status: "reserved",
    createdAt: "2024-01-03",
  },
]

export const plots: Plot[] = [
  {
    id: "plot-001",
    title: "Premium Plot in Kigali Heights",
    price: 45000000, // RWF
    size: 800,
    location: "Kigali Heights, Gasabo",
    coordinates: { lat: -1.9441, lng: 30.0619 },
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Prime residential plot with stunning mountain views, perfect for building your dream home.",
    features: ["Mountain View", "Electricity Available", "Water Connection", "Paved Road Access", "Security"],
    status: "available",
    createdAt: "2024-01-15",
  },
  {
    id: "plot-002",
    title: "Commercial Plot in Kimisagara",
    price: 85000000,
    size: 1200,
    location: "Kimisagara, Nyarugenge",
    coordinates: { lat: -1.9706, lng: 30.0588 },
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Strategic commercial plot in busy Kimisagara area, ideal for business development.",
    features: ["Corner Plot", "High Traffic Area", "Commercial Zoning", "Public Transport", "Utilities Ready"],
    status: "available",
    createdAt: "2024-01-10",
  },
  {
    id: "plot-003",
    title: "Residential Plot in Gacuriro",
    price: 32000000,
    size: 600,
    location: "Gacuriro, Gasabo",
    coordinates: { lat: -1.9167, lng: 30.1333 },
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Quiet residential plot in the growing Gacuriro area, perfect for family homes.",
    features: ["Quiet Neighborhood", "School Nearby", "Flat Terrain", "Electricity", "Water Access"],
    status: "available",
    createdAt: "2024-01-20",
  },
  {
    id: "plot-004",
    title: "Luxury Plot in Nyarutarama",
    price: 120000000,
    size: 1500,
    location: "Nyarutarama, Gasabo",
    coordinates: { lat: -1.9333, lng: 30.1167 },
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Exclusive plot in prestigious Nyarutarama with lake views and premium amenities.",
    features: ["Lake View", "Gated Community", "Premium Location", "Large Size", "Luxury Neighborhood"],
    status: "reserved",
    createdAt: "2024-01-05",
  },
]


export const testimonials: Testimonial[] = [
  {
    id: "test-001",
    name: "Jean Baptiste Uwimana",
    image: "/placeholder.svg?height=80&width=80",
    quote:
      "HKN Real Estate helped me find the perfect plot for my dream home. Their service was exceptional and professional throughout the entire process.",
    rating: 5,
    location: "Kigali Heights",
  },
  {
    id: "test-002",
    name: "Marie Claire Mukamana",
    image: "/placeholder.svg?height=80&width=80",
    quote:
      "I purchased a beautiful villa through HKN Real Estate. The team was knowledgeable and made the buying process smooth and stress-free.",
    rating: 5,
    location: "Nyarutarama",
  },
  {
    id: "test-003",
    name: "David Nkurunziza",
    image: "/placeholder.svg?height=80&width=80",
    quote:
      "Excellent service! They found me the perfect commercial plot for my business. I highly recommend HKN Real Estate to anyone looking for property in Rwanda.",
    rating: 5,
    location: "Kimisagara",
  },
]
