import type { Plot, Testimonial } from './types';

export const plots: Plot[] = [
  {
    id: 'plot-1',
    name: 'Green Valley Estate',
    location: 'Springfield, IL',
    price: 150000,
    sizeSqFt: 10000,
    imageUrl: '/placeholder.svg?height=400&width=600',
    description: 'A beautiful, spacious plot perfect for building your dream home, surrounded by lush greenery.',
    availability: 'available',
    coordinates: { lat: 39.7817, lng: -89.6501 },
  },
  {
    id: 'plot-2',
    name: 'Riverside View',
    location: 'Rivertown, CA',
    price: 220000,
    sizeSqFt: 15000,
    imageUrl: '/placeholder.svg?height=400&width=600',
    description: 'Prime riverside property with stunning views and direct access to the water. Ideal for a luxury build.',
    availability: 'available',
    coordinates: { lat: 38.5758, lng: -121.4788 },
  },
  {
    id: 'plot-3',
    name: 'Mountain Crest',
    location: 'Boulder, CO',
    price: 180000,
    sizeSqFt: 12000,
    imageUrl: '/placeholder.svg?height=400&width=600',
    description: 'Elevated plot offering panoramic mountain views, perfect for a secluded retreat.',
    availability: 'reserved',
    coordinates: { lat: 40.0150, lng: -105.2705 },
  },
  {
    id: 'plot-4',
    name: 'City Edge Lot',
    location: 'Metropolis, NY',
    price: 300000,
    sizeSqFt: 8000,
    imageUrl: '/placeholder.svg?height=400&width=600',
    description: 'Conveniently located near the city center, this plot offers urban accessibility with space.',
    availability: 'available',
    coordinates: { lat: 40.7128, lng: -74.0060 },
  },
  {
    id: 'plot-5',
    name: 'Forest Haven',
    location: 'Pine Ridge, OR',
    price: 130000,
    sizeSqFt: 11000,
    imageUrl: '/placeholder.svg?height=400&width=600',
    description: 'A tranquil plot nestled within a serene forest, offering privacy and natural beauty.',
    availability: 'available',
    coordinates: { lat: 44.0582, lng: -121.3153 },
  },
  {
    id: 'plot-6',
    name: 'Sunset Mesa',
    location: 'Red Rock, AZ',
    price: 195000,
    sizeSqFt: 13500,
    imageUrl: '/placeholder.svg?height=400&width=600',
    description: 'Stunning desert landscape with breathtaking sunset views, ideal for a unique architectural design.',
    availability: 'sold',
    coordinates: { lat: 34.0489, lng: -111.0937 },
  },
];

export const testimonials: Testimonial[] = [
  {
    id: 'test-1',
    clientName: 'Alice Johnson',
    quote: 'HKN Real Estate helped me find the perfect plot for my dream home. Their service was exceptional!',
    clientImageUrl: '/placeholder.svg?height=100&width=100',
  },
  {
    id: 'test-2',
    clientName: 'Bob Williams',
    quote: 'Professional, knowledgeable, and truly dedicated. HKN Real Estate made the land buying process seamless.',
    clientImageUrl: '/placeholder.svg?height=100&width=100',
  },
  {
    id: 'test-3',
    clientName: 'Carol Davis',
    quote: 'I highly recommend HKN Real Estate. They have a fantastic selection of plots and their team is incredibly supportive.',
    clientImageUrl: '/placeholder.svg?height=100&width=100',
  },
];
